const ApiUrl = 'https://huiguanjia.dd371.com/api/'
const ApiLocation = 'https://apis.map.qq.com/ws/location/v1/ip?key=I7LBZ-CD4KD-DMN4Q-P5FYP-V2DOV-PWBM2'

module.exports = {
  ApiLocation: ApiLocation,
  ApiLogin: ApiUrl + 'login/login',
  ApiLoginIndex: ApiUrl + 'login/index',
  ApiLoginCode: ApiUrl + 'login/getcode',
  ApiLoginForget: ApiUrl + 'login/forget_get_code',
  ApiLoginUsave: ApiUrl + 'login/usave',
  ApiIndex: ApiUrl + 'index/index',
  ApiIndexSave: ApiUrl + 'index/save',
  ApiDemand: ApiUrl + 'index/demand',
  ApiNearby: ApiUrl + 'hotel/nearby',
  ApiSaveDemand: ApiUrl + 'index/save',
  ApiDetail: ApiUrl + 'hotel/detail',
  ApiRoomDetail: ApiUrl + 'hotel/room_detail',
  ApiAssess: ApiUrl + 'hotel/assess',
  ApiCity: ApiUrl + 'hotel/city',
  ApiLister: ApiUrl + 'hotel/lister',
  ApiHotelSearch: ApiUrl + 'hotel/serach_term',
  ApiHotelSearchLister: ApiUrl + 'hotel/search_lister',
  ApiApply: ApiUrl + 'user/apply',
  ApiProblemLister: ApiUrl + 'user/problem',
  ApiProblemDetail: ApiUrl + 'user/problem_detail',
  ApiUserIndex: ApiUrl + 'user/index',
  ApiUserFriends: ApiUrl + 'user/friends_lister',
  ApiUserSave: ApiUrl + 'user/save',
  ApiUserTeam: ApiUrl + 'user/my_first_team',
  ApiUserMyTeam: ApiUrl + 'user/my_team',
  ApiUserTeamDetail: ApiUrl + 'my_first_team_detail',
  ApiUserCash: ApiUrl + 'user/cash',
  ApiUserCashSave: ApiUrl + 'index/cash_save',
  ApiUserCashLog: ApiUrl + 'user/cash_log',
  ApiUserAssessSave: ApiUrl + 'user/save_assess',
  ApiUserMy_dd: ApiUrl + 'user/my_dd',
  ApiUserDd_detail: ApiUrl + 'user/dd_detail',
  ApiBuyOrder: ApiUrl + 'buy/order',
  ApiBuySave: ApiUrl + 'buy/save'
}